"""added cols created at updated at deleted at

Revision ID: 56ae16e85029
Revises: af41ceccd0c0
Create Date: 2026-05-23 10:58:30.590407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ae16e85029'
down_revision: Union[str, None] = 'af41ceccd0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
